apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
spec:
  destination:
    name: ''
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: demo-app
    repoURL: 'https://github.com/michaelkotelnikov/argocd-playground.git'
    targetRevision: HEAD
  sources: []
  project: demo

