
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bimbamam
  namespace: nikita-gitops
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kv/example-push-secret
        property: token
      secretKey: example-yolo
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
