apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: nikita-gitops
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 2Gi