apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mariadb-appset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/michaelkotelnikov/argocd-playground
      revision: master
      directories:
      - path: mariadb-resources/*
  template:
    metadata:
      name: 'mariadb-{{path.basename}}'
      namespace: ebutz
    spec:
      project: default
      source:
        repoURL: https://github.com/michaelkotelnikov/argocd-playground.git
        targetRevision: master
        path: 'mariadb-resources/{{path.basename}}'
      destination:
        name: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
